name: AWS OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws-authentication:
    name: Probar autenticación AWS
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar identidad del repositorio
        run: |
          echo "Owner: ${{ github.repository_owner }}"
          echo "Owner ID: ${{ github.repository_owner_id }}"
          echo "Repository: ${{ github.repository }}"
          echo "Repository ID: ${{ github.repository_id }}"
          echo "Branch: ${{ github.ref }}"

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::712934829117:role/github-actions-cicd-practice
          aws-region: us-east-1
