name: AWS OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws-authentication:
    name: Probar autenticación AWS
    runs-on: ubuntu-latest

    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::712934829117:role/github-actions-cicd-practice
          aws-region: us-east-1
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Mostrar identidad AWS
        run: aws sts get-caller-identity
