name: Mi primer workflow

on:
  push:
  workflow_dispatch:

jobs:
  aprender:
    runs-on: ubuntu-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Leer archivo del repositorio
        run: cat mensaje.txt
      
      - name: Mostrar saludo
        run: echo "Hola, estoy ejecutando mi primer GitHub Action"

      - name: Mostrar sistema operativo
        run: uname -a

      - name: Mostrar directorio actual
        run: pwd

      - name: Mostrar usuario del runner
        run: whoami

      - name: Mostrar información del evento
        run: |
          echo "Repositorio: ${{ github.repository }}"
          echo "Rama o referencia: ${{ github.ref }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Usuario: ${{ github.actor }}"

  mi_ip:
    runs-on: ubuntu-latest
    needs: aprender

    steps:
      - name: Esta es mi IP
        run: ifconfig
        
