name: Mi primer workflow

on:
  push:
  workflow_dispatch:

jobs:
  aprender:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar saludo
        run: echo "Hola, estoy ejecutando mi primer GitHub Action"

      - name: Mostrar sistema operativo
        run: uname -a

      - name: Mostrar directorio actual
        run: pwd

      - name: Mostrar usuario del runner
        run: whoami
