name: Terraform CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "~1.16.0"

      - name: Verificar formato
        run: terraform fmt -check -recursive -diff -no-color

      - name: Inicializar Terraform
        run: terraform init -backend=false -input=false

      - name: Validar Terraform
        run: terraform validate -no-color

      - name: Generar plan
        run: terraform plan -input=false -out=tfplan

      - name: Mostrar plan
        run: terraform show -no-color tfplan

      - name: Guardar plan como artifact
        uses: actions/upload-artifact@v7
        with:
          name: terraform-plan
          path: terraform/tfplan
          if-no-files-found: error
          retention-days: 1

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "~1.16.0"

      - name: Inicializar Terraform
        run: terraform init -backend=false -input=false

      - name: Descargar plan
        uses: actions/download-artifact@v8
        with:
          name: terraform-plan
          path: terraform

      - name: Aplicar plan
        run: terraform apply -input=false -auto-approve tfplan

      - name: Mostrar outputs
        run: terraform output

      - name: Inspeccionar estado
        run: |
          echo "Archivo de estado:"
          ls -lh terraform.tfstate

          echo "Recursos administrados:"
          terraform state list

          echo "Outputs:"
          terraform output

      - name: Comprobar segundo plan
        run: terraform plan -input=false -no-color

      - name: Aplicar plan
        run: terraform apply -input=false -auto-approve tfplan

      - name: Inspeccionar estado
        run: |
          echo "Archivo de estado:"
          ls -lh terraform.tfstate

          echo "Recursos administrados:"
          terraform state list

          echo "Outputs:"
          terraform output

      - name: Comprobar segundo plan
        run: terraform plan -input=false -no-color
