name: Terraform CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  terraform-validation:
    name: Validar Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "~1.16.0"

      - name: Mostrar versión
        run: terraform version

      - name: Verificar formato
        run: terraform fmt -check -recursive -diff -no-color

      - name: Inicializar Terraform
        run: terraform init -backend=false -input=false

      - name: Validar Terraform
        run: terraform validate -no-color

      - name: Generar Terraform Plan
        run: terraform plan -no-color -input=false
